Test controllers
bamsi/myblog pull request #5
Opened 2022-09-03 16:31 UTC by bamsi

In this pull request, I have implemented the following:
- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.
  Your code review is appreciated!

2022-09-03 16:54 UTC, medaminedev66 requested changes
Hi @bamsi  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional 
- You have a descriptive PR 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 16:54 UTC, medaminedev66 commented on spec/controllers/posts_spec.rb
> +require 'rails_helper'
- [ ] Following the project requirements, your project should Have `users_spec.rb` and `posts_spec.rb` in `spec/requests/` directory.

2022-09-03 16:54 UTC, medaminedev66 commented on spec/controllers/posts_spec.rb
> +RSpec.describe PostsController, type: :controller do
- [ ] Following the project requirements, you should use `type: request` as shown in the example code below OR use `config.infer_spec_type_from_file_location!` in the Rspec config file (in that case just placing a file in the `spec/requests` dir will be enough).
```ruby
RSpec.describe "Users", type: :request do
   ...
 end
```

2022-09-03 16:54 UTC, medaminedev66 commented on spec/controllers/posts_spec.rb
> +      expect(subject).to render_template('show')
- [ ] Following the project requirements, make sure that for each action you check:
- If response status was correct.
- If a correct template was rendered.
- If the response body includes correct placeholder text.

All your tests fail, please work on correcting them:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/77190203/188280685-1cc4212e-d1a0-4fc5-8447-939b831fbf99.png">

2022-09-03 19:22 UTC, phelian23 requested changes
Hi @bamsi,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 19:22 UTC, phelian23 commented on spec/requests/posts_spec.rb
> +
- [ ] Good job working on the changes requested by the previous reviewer, however, your test is still failing.
![Capture](https://user-images.githubusercontent.com/85095702/188285082-f8357a39-1a81-4090-9d5e-19a30d103204.PNG)

- [ ] Check your models. the validate method should be `validates` and not `Validate`

2022-09-09 08:44 UTC, BenMukebo requested changes
Hi @bamsi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Good job working on the changes requested by the previous reviewer, however, your test is still failing, please work on correcting them:

![18](https://user-images.githubusercontent.com/79058364/189309898-b861eb32-3ead-4545-818d-3ed3dca0b1fa.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 09:51 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @bamsi , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

**All the tests are running successfully** 🎉 


Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 10:37 UTC, merged